### ISSUE TITLE
Work without #?replace()

### ISSUE THREAD

**Issue by juancarlospaco** [Yardanico/nuglifier#1]
- New `--eval:` allows to work without the `#? replace("A","B") | replace("A","B")`

```nim
#  ~/.config/nim/config.nims
from std/strutils import multiReplace

const replacements = [
  ("say", "echo"),
]

task uglify, "???":
  setCommand("c")
  switch("eval", paramStr(2).readFile.multiReplace replacements)
```

```nim
# file.nim
say 42
```

```console
$ nim uglify file.nim
```

**Comment by Yardanico** [comment]
I don't think that this is useful. The point of nuglifier is to transform a source file into an uglified file that will work the same way the source file did without having to do any extra work.
Sorry, but closing as wontfix.
